site_name: 服务器必看文档
theme:
  name: material
  language: zh
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.blocks.admonition:
      types:
        - note
        - warning
        - info
        - tip
        - danger
nav:
  - 首页: index.md
  - 网站必看: website.md
  - 关于: about.md
